sogilis/Blog

Dockerfile

fix: Hugo binary permission in Dockerfile

---

.gitignore
Dockerfile

chore: remove Hugo binaries from repository + upgrade to extended version

---

site/config.toml
site/themes/sogilis/layouts/index.html

Pagination can be added later after blog is live.

Remove pagination

---

Makefile
README.md
site/config.toml

Language will be detected from hostname (instead of path).
See [Hugo documentat](https://gohugo.io/content-management/multilingual/#configure-multilingual-multihost) for more details.

Multilingual Multihost

---

Makefile
README.md
site/config.toml

Reverts sogilis/Blog#46 because it may have broken the blog

Revert "Multilingual Multihost"

---

README.md

doc: fix emojis and remove contributors

---

site/themes/sogilis/assets/sass/576-767.scss
site/themes/sogilis/assets/sass/768-991.scss
site/themes/sogilis/assets/sass/992-1199.scss
site/themes/sogilis/assets/sass/inf576.scss

fix: remove left margin in article content on <em> and <Strong>

---

yarn.lock

`yarn upgrade` fix #77

---

yarn.lock

`yarn upgrade` Fix vulnerabilities

---

site/themes/sogilis/assets/css/header.css
site/themes/sogilis/layouts/_default/baseof.html
site/themes/sogilis/layouts/partials/head.html
site/themes/sogilis/layouts/partials/header.html

Fix #84 
Change display according to @nicolaserre discussion on Friday

Header: fix display bug in some screen size (#84) + align logo and nav to main content

---

site/themes/sogilis/assets/css/header.css
site/themes/sogilis/assets/css/index-page.css
site/themes/sogilis/layouts/_default/summary.html

[UI] fix card display problem on Chromium and Safari (Fix #122 )

[UI] fix card display problem on Chromium and Safari (Fix #122 )

---

site/themes/sogilis/assets/css/header.css

[UI] Fix #121 Menu styling has changed

[UI] Fix #121 Menu styling has changed

---

site/themes/sogilis/assets/css/header.css
site/themes/sogilis/layouts/index.html
site/themes/sogilis/layouts/partials/header.html

Fix flying header does not 100% width (fix #117)

Fix flying header does not 100% width (Fix #117)

---

site/themes/sogilis/assets/css/header.css

Fix menu dropdown is too slow (fix #120)

Fix menu dropdown is too slow (fix #120)

---

site/themes/sogilis/assets/css/index-page.css

Improve display of the css grid (fix #127)

Improve display of the css grid (fix #127)

---

site/themes/sogilis/assets/css/header.css

[ui][navbar] increase margin-top dropdown (fix #129)

[ui][navbar] increase margin-top dropdown (fix #129)

---

README.md

Typos and bad links

---

site/themes/sogilis/assets/css/index-page.css
site/themes/sogilis/layouts/_default/summary.html

Suggestion d'amélioration du style CSS du composant `blog_index_article` en utilisant BEM.

Suggestion: refactor blog_index_article component style with BEM

---

.editorconfig
.eslintignore
.eslintrc.yml
.gitignore
.prettierignore
.prettierrc
Makefile
README.md
package.json
site/static/admin/config.yml
site/static/admin/index.html
site/static/manifest.json
site/themes/sogilis/assets/css/article.css
site/themes/sogilis/assets/css/footer.css
site/themes/sogilis/assets/css/header-inf767.css
site/themes/sogilis/assets/css/header-sup768.css
site/themes/sogilis/assets/css/header.css
site/themes/sogilis/assets/css/index-page.css
site/themes/sogilis/assets/css/shared.css
site/themes/sogilis/layouts/_default/baseof.html
site/themes/sogilis/layouts/_default/single.html
site/themes/sogilis/layouts/_default/summary.html
site/themes/sogilis/layouts/index.html
site/themes/sogilis/layouts/partials/footer.html
site/themes/sogilis/layouts/partials/head.html
site/themes/sogilis/layouts/partials/header.html
site/themes/sogilis/static/js/scripts.js
yarn.lock

À cause du format imposé par Hugo pour les fichiers Markdown. Prettier explose sur les fichiers en .md lol.  .
Le problème est dû à la syntaxe `{{ highlight }}` (transformée en balise `<pre>`). On ne voudrait pas que prettier agisse entre les balise `{{highlight}}`, parce que ça pète toute la mise en page.
VuePress n'utilise pas la syntaxe `{{ highlight }}` mais la syntaxe classique 
<pre>
```anyLanguage
```
</pre>
J'ai pas trouvé de fixes. 
Y'a juste ça https://discourse.gohugo.io/t/hugo-and-prettier/22596  ou https://discourse.gohugo.io/t/anyone-fancy-creating-go-plugin-for-prettier/10388 , mais ça ne résoud pas notre problème. 
À noter que même en essayant de les configurations proposées, on ne peut pas non plus linter leur template HTML. On a l'erreur suivante:
``` …
```

Add Prettier + Husky

---

site/content/posts/2014-01-29-histoire-4-premiers-mois-sogilis.md
site/content/posts/2014-03-11-management-sans-manager-sogilis.md
site/content/posts/2014-04-10-retrospective-mensuelle.md
site/content/posts/2016-12-13-sogimood-appli-sante-projets.md
site/themes/sogilis/layouts/shortcodes/disclaimer.html

And we add disclaimer shortcode cf https://gohugo.io/templates/shortcode-templates/

Add disclaimer on posts that need it

---

README.md
docs/dev.md
docs/docker.md
docs/prerequisites.md

doc: simplify README.md

---

README.md
docs/content-format.md

Fix #185
ℹ️ Un test a été fait pour vérifier le format accepté : https://github.com/sogilis/Blog/pull/184/files

doc: describe the content format in details

---

.github/workflows/scheduled.yml

cron: change slack notif icon

---

package.json
yarn.lock

`$ yarn upgrade --latest`

---

site/themes/sogilis/assets/css/article.css

fix with of <blockquote> and <pre> with small screens

---

.eslintrc.yml
.gitignore
package.json
site/config.toml
site/themes/sogilis/assets/css/header-inf767.css
site/themes/sogilis/assets/css/header-sup768.css
site/themes/sogilis/assets/css/header.css
site/themes/sogilis/assets/css/index-page.css
site/themes/sogilis/layouts/_default/list.json.json
site/themes/sogilis/layouts/partials/head.html
site/themes/sogilis/layouts/partials/header.html
site/themes/sogilis/layouts/partials/scripts.html
site/themes/sogilis/static/js/scripts.js
yarn.lock

feature: add search

---

netlify.toml
package.json
yarn.lock

See also https://github.com/sogilis/Blog/pull/233

Fix vulnerabilities: `yarn upgrade --latest`

---

.eslintrc.yml
README.md
site/themes/sogilis/assets/css/footer.css
site/themes/sogilis/assets/css/shared.css
site/themes/sogilis/i18n/fr.toml
site/themes/sogilis/layouts/partials/footer.html
site/themes/sogilis/layouts/partials/head.html
site/themes/sogilis/static/js/scripts.js

Add Google Analytics and tarteaucitronjs

---

.github/workflows/scheduled.yml
README.md
docs/dev.md
site/content/posts/2016-03-03-bookmarks-bla-bla-2.md
site/themes/sogilis/static/js/scripts.js
site/themes/sogilis/theme.toml

`$ find -path './node_modules' -prune -o -path './.git' -prune -o -type f -exec sed -i 's/sogilis.fr/sogilis.com/' {} +`

feat: correct link from sogilis.fr to sogilis.com 

---

site/static/admin/config.yml

Voici ce que ça donne (sur https://deploy-preview-251--wizardly-roentgen-e7f07e.netlify.app/admin) :

Add author field in admin

---

package.json
yarn.lock

Hugo v0.81.0 adds support to mac ARM

Add support to mac ARM
